### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Anaminus** [Anaminus/rbxpipe#1]
- [x] Implement automatic search for studio executable.
- [x] Implement XML format.
- [x] Implement timeout option.
- [x] Add option to emulate Play Solo mode.
- [x] Compile builds for Windows. Research cross compilation for other platforms.
